# Generated by Django 5.1.3 on 2026-05-15 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_customuser_middle_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Volunteer', 'Ерікті'), ('Client', 'Клиент'), ('Admin', 'Әкімші')], default='Client', max_length=20),
        ),
        migrations.AlterField(
            model_name='helprequest',
            name='category',
            field=models.CharField(choices=[('Food', 'Азық-түлік'), ('Medicine', 'Дәрі-дәрмек'), ('Cleaning', 'Тазалау'), ('Financial', 'Қаржылай көмек'), ('Other', 'Басқа')], max_length=50),
        ),
        migrations.AlterField(
            model_name='helprequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Күтуде'), ('Review', 'Қаралуда'), ('Process', 'Өңдеуде'), ('Completed', 'Орындалды'), ('Rejected', 'Бас тартылды')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='volunteerapplication',
            name='status',
            field=models.CharField(choices=[('Pending', 'Күтуде'), ('Approved', 'Қабылданды'), ('Rejected', 'Бас тартылды')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='volunteertask',
            name='status',
            field=models.CharField(choices=[('Scheduled', 'Жоспарланды'), ('In-Progress', 'Орындау үстінде'), ('Completed', 'Орындалды')], default='Scheduled', max_length=20),
        ),
    ]
