# Generated by Django 5.1.3 on 2026-05-15 18:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_customuser_role_alter_helprequest_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title_kk', models.CharField(max_length=200)),
                ('title_ru', models.CharField(blank=True, default='', max_length=200)),
                ('body_kk', models.TextField(blank=True, default='')),
                ('body_ru', models.TextField(blank=True, default='')),
                ('is_published', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='NewsPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_kk', models.CharField(max_length=200)),
                ('title_ru', models.CharField(blank=True, default='', max_length=200)),
                ('body_kk', models.TextField(blank=True, default='')),
                ('body_ru', models.TextField(blank=True, default='')),
                ('cover_image_url', models.URLField(blank=True, default='')),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
