# Generated by Django 5.1.3 on 2026-05-19 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_contentpage_newspost_alter_customuser_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteertask',
            name='address',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='volunteertask',
            name='category',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='volunteertask',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='volunteertask',
            name='help_request',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='volunteer_task', to='core.helprequest'),
        ),
    ]
