# Generated by Django 6.0.5 on 2026-05-25 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_volunteertask_address_volunteertask_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspost',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='news_covers/'),
        ),
    ]
