# Generated by Django 5.1.3 on 2026-05-25 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
